:Author: zmanita
:Email:
:Date: 26/11/2023
:Revision: version#2
:License: Public Domain

= Project: {Project}

This project displays a message (on Morse code) sent to an Arduino board from the messenger widget on the Arduino IoT cloud. 

== Step 1: Installation
1. Download and run the zip code like any other Arduino code.
(Import all your sketches and libraries at once:
Compress the Arduino folder that contains all your sketches and custom libraries in .Zip format.
Make sure your libraries are in a folder called ‘libraries’. Be sure not to mix sketches and libraries in the same folder.
Remember that you can import libraries just in .Zip, while sketches can be in .Zip, .Ino or .Pde)

2. This sketch file is for running on desktop apps, although it was originally created to run on the Arduino web editor. To run on the web editor, read through the code Untitled_nov26c.ino and add all the necessary variables as "Arduino Things" on the cloud. 

== Step 2: Assemble the circuit

Assemble the circuit following the diagram LedCircuit.png attached to the sketch. Change the digital pin number according to the code.

== Step 3: Load the code

Upload the code contained in this sketch onto your board.
